### ISSUE TITLE
weird result of KITTI15

### ISSUE THREAD

**Issue by buaaJeremyduan** [mattpoggi/guided-stereo#1]
![D1 all ](https://user-images.githubusercontent.com/15872983/59025930-dfe80c80-8887-11e9-92d4-72814859c26b.png)
I obtian the coresponding lidar from the Kitti Odometry dataset. The weight I use is PSMNet-ft-gd-tr.

**Comment by mattpoggi** [comment]
Hi @buaaJeremyduan ,
which image is from KITTI15? Be also sure the lidar points are correctly aligned to the image

**Comment by buaaJeremyduan** [comment]
Thanks for replay. I test 142 images of KITTI15 and most of the result is below 2%(3 px error).  The top left image is from KITTI15(000049_10.png) and the error is mainly in the left bottom of the image. I double check the projected lidar and find disalignment between the lidar and image. So in other words, this algothrim is very sensetive to this kind of disalignment.

**Comment by mattpoggi** [comment]
Thanks for pointing it out :) anyway, on very few frames some artifacts occur (you can notice it in our youtube video as well), but this one seems particularly large, I will take a look at that.

**Comment by Lvhhhh** [comment]
> Thanks for replay. I test 142 images of KITTI15 and most of the result is below 2%(3 px error). The top left image is from KITTI15(000049_10.png) and the error is mainly in the left bottom of the image. I double check the projected lidar and find disalignment between the lidar and image. So in other words, this algothrim is very sensetive to this kind of disalignment.

hi,when you use the weight of PSMNet-ft-gd-tr . do you have the error of 'unexcepted keys in statr_dict: num_batches_tracked'? how do you fix it ,and the pytorch you use is 0.4.0??
