### ISSUE TITLE
this method is not well in no texture area likes sky

### ISSUE THREAD

**Issue by Lvhhhh** [mattpoggi/guided-stereo#3]
compare the results of psmnet-ft.tar and psmnet-ft-gd-tr.tar
find it does not work well in no texture areas like sky.
but it improve the details in hollowed out area
![000055](https://user-images.githubusercontent.com/13911923/59410128-9305b800-8dea-11e9-966a-c5137272c702.png)

![000055](https://user-images.githubusercontent.com/13911923/59410134-97ca6c00-8dea-11e9-9882-967d7d6caa48.png)
above is the psmnet-ft and below is psmnet-ft-gd-tr

**Comment by Lvhhhh** [comment]
and the edge of the car is not well 
![000100](https://user-images.githubusercontent.com/13911923/59410221-dd873480-8dea-11e9-908c-640b6bc92d9b.png)
![000100](https://user-images.githubusercontent.com/13911923/59410223-e1b35200-8dea-11e9-9710-76a906aeeaee.png)
the order of results  is the same

**Comment by mattpoggi** [comment]
Hello,
The guided network is trained with about 5% density. When the sparsity becomes much higher (e.g., in the sky where no points are available) the network performance is slightly worse, of course. The same occurs for the car in your image.
