### ISSUE TITLE
Some questions concerning the evaluation metrics

### ISSUE THREAD

**Issue by MrZilinXiao** [mattpoggi/guided-stereo#5]
![image](https://user-images.githubusercontent.com/42504790/117429220-67999280-af59-11eb-8820-cb0dde62ec44.png)
Hi! Thank you for your impressive work on guided-stereo! I was so curious that I have to ask which part of dataset you evaluate your work and peer competitors on? I find no trace of these results on KITTI2015 leaderboard.

**Comment by mattpoggi** [comment]
Hi, the experiments are carried out on the KITTI 2015 training dataset, since the testing data do not provide depth maps to be used as guide.

**Comment by MrZilinXiao** [comment]
Thank you for your reply.
